# Global setting for all debugging.
debug: false




# Configuration for minecraft
minecraft:

  # Account that will be proxied (the bot connects via this)
  # Documentation: https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#mineflayercreatebotoptions
  # All options from that are valid.
  account:
    username: #name
    auth: microsoft

  # Custom implementation of a SOCKS4/5 proxy.
  proxy:
    enabled: false
    # protocol: socks5
    # info:
    #   host: 1.1.1.1
    #   port: 8080


  # The server we wish to connect to.
  # This will override options in "account".
  remoteServer:
    host: 2b2t.org
    port: 25565
    version: 1.12.2


# Minecraft-protocol configuration for our local server.
# Documentation: https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#mineflayercreatebotoptions
# All options from there are valid.
localServer:
  host: 0.0.0.0
  port: 25565
  version: 1.12.2
  online-mode: false
  maxPlayers: 1

# Custom settings for the local server.
localServerConfig:

  # milliseconds until next attempt to reconnect
  reconnectInterval: 10000

  # disable all commands.
  disableCommands: false

  # Experimental, but does work. (Some commands break)
  disconnectAllOnEnd: false
  restartOnDisconnect: true
  linkOnConnect: true

  # Security: who is allowed to join. Null for anyone.
  security:
    allowList: null
    kickMessage: Default kick message

  display:
    motdPrefix: "§6"
    proxyChatPrefix: "§6>>P§r "

    # Has to be 64x64 and a png.
    # Can be a file path or a URL.
    favicon: ./static/assets/2b2w-small.png

  spectator:
    logPlayerJoinLeave: false


  # AntiAFK options.
  antiAFK:

    enabled: true

    # AntiAFK module settings. Leave this be for now.
    # I will include documentation at a later date.
    modules:

      WalkAroundModule:
        timeout: 5000

      RandomMovementModule:
        enabled: false

      ChatBotModule:
        enabled: false

    # AntiAFK passive settings. Leave this be for now.
    # I will include documentation at a later date.
    passives:
      KillAuraPassive:
        playerWhitelist: []
        reach: 4
        multi: false
        enabled: true

  # Auto eat toggle     
  autoEat: true


# Discord logging settings.
discord:

  # Discord bot configuration.
  bot:
    enabled: false
    # token: 
    # prefix: 


  # Discord webhook configuration.
  # Usage: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  webhooks:
    enabled: true

    gameChat:
      url: "" # empty url = specific webhook disabled
      icon: ""
      username: Game chat
      timestamp: true

    serverInfo:
      url: ""
      icon: ""
      username: Server info

    queue:
      reportAt: 500
      url: ""
      icon: ""
      username: Queue
      edit: true # edit webhook message after first sent. Defaults to false




logger:
  enabled: false
