# 2b2w initial settings
debug: false
startImmediately: true
pluginFolder: './plugins'

# Configuration for minecraft
minecraft:

  # Account that will be proxied (the bot connects via this)
  # Documentation: https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#mineflayercreatebotoptions
  # All options from that are valid.
  account:
    username: 
    auth: microsoft

  # Custom implementation of a SOCKS4/5 proxy.
  proxy:
    enabled: false
    # protocol: socks5
    # info:
    #   host: 1.1.1.1
    #   port: 8080


  # The server we wish to connect to.
  # This will override options in "account".
  remoteServer:
    host: 2b2t.org
    port: 25565
    version: 1.12.2


# Minecraft-protocol configuration for our local server.
# Documentation: https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#mineflayercreatebotoptions
# All options from there are valid.
localServer:
  host: 0.0.0.0
  port: 25566
  version: 1.12.2
  online-mode: false
  maxPlayers: 1

# Custom settings for the local server.
localServerConfig:


  whitelist: null
  kickMessage: Not whitelisted, leave.


  # milliseconds until next attempt to reconnect
  reconnectInterval: 10000

  # disable all commands.
  disableCommands: false

  # Experimental, but does work. (Some commands break)
  disconnectAllOnEnd: true
  restartOnDisconnect: true
  linkOnConnect: true


  motdPrefix: "§6"
  proxyChatPrefix: "§6>>P§r "

  # Has to be 64x64 and a png.
  # Can be a file path or a URL.
  favicon: ./static/assets/2b2w-small.png

  # AntiAFK options.
  antiAFK:

    enabled: true

    # AntiAFK module settings. Leave this be for now.
    # I will include documentation at a later date.
    modules:
      SwingArm:
        enabled: true
      
      BoxWalk:
        enabled: true
        distance: 16
        travelTime: 5000
        waitTime: 30000 # wait 30 seconds before turning/walking

    # AntiAFK passive settings. Leave this be for now.
    # I will include documentation at a later date.
    passives:
      KillAura:
        playerWhitelist: []
        reach: 4
        multi: false
        enabled: false

  # Auto eat toggle     
  autoEat: true








# Discord logging settings.
discord:

  # Discord bot configuration.
  bot:
    enabled: false
    # token: 
    # prefix: "!"


  # Discord webhook configuration.
  # Usage: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  webhooks:
    enabled: false

    eventConfig:
      started:  
        deleteEvents: ["stopped", "leftQueue", "enteredQueue", "queueUpdate"]

      stopped:
        deleteEvents: ["started", "leftQueue", "enteredQueue", "queueUpdate"]

      queueUpdate:
        reportAt: 500
        edit: true # edit webhook message after first sent. Defaults to false

      botevent_chat:
        skipFooter: true
        skipTitle: false
        timestamp: true

      leftQueue:
      
      enteredQueue:

      linking:

      unlinking:


    # Webhooks have been overhauled.
    # List as many webhooks as you'd like and list the events that go to that webhook below.
    webhooks: [
      # {
        # url: ,
        # wantedEvents: ["botevent_chat"],
        # icon: ,
        # username: Game chat,
     # },
    ]
 
       


 




logger:
  enabled: false

  filters: 
    localServerSend: 
      blacklist: ['map*']
    
    remoteBotReceive: 
      blacklist: ['map*']
  
  

