
bot:
  enabled: false
  botToken: MTA1Nzc4NjAxOTc5OTM4MDA1OQ.G6qVVV.Rl478Cq3k-iIyf-Y3LAbU_6WT6GN607Md3PDl0
  prefix: "!"

webhooks:
  enabled: true

  gameChat:
    url: https://discord.com/api/webhooks/1088894870569103493/xX5auwxqly71oSbwnHc2FXYU91y8-Hhnqf8o6teLIPbdj4NK5NIA1EVBO50jMTYz992B
    username: Game chat

  serverInfo:
    url: https://discord.com/api/webhooks/1088895214233583616/EYCY1yYwSgplczE7Fvu09_hcF1OReVIoEYH53oOwghB_5KRqmGyan9wMGlo9PpjlcfZm
    username: Server info

  queue:
    reportAt: 100
    url: https://discord.com/api/webhooks/1088895149628719277/EWaUJwcART1Nj2n6YF2aDo2CZuKiuNx2dFi09KCVf6OItSEB4z3xvQYevCQ2wPifluNb
    username: Queue
