# Publish GitHub workflow artifacts tutorial example
name: Build To Executable

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create a temporary artifact downloads folder
        run: mkdir pkg
        
      - name: Install all packages
        run: npm install

      - name: Build package to binaries
        run: npx pkg . --target node16-linux-x64
    
      - name: Use the Upload Artifact GitHub Action (Linux)
        uses: actions/upload-artifact@v2
        with: 
          name: 2b2w-ts-rewrite-linux
          path: pkg

      - name: Reset and build package to binaries
        run: rm -rf pkg/* && npx pkg . --target node16-macos-x64
    
      - name: Use the Upload Artifact GitHub Action (MacOS)
        uses: actions/upload-artifact@v2
        with: 
          name: 2b2w-ts-rewrite-macos
          path: pkg

      - name: Reset and build package to binaries
        run: rm -rf pkg/* && npx pkg . --target node16-win-x64

      - name: Use the Upload Artifact GitHub Action (Windows)
        uses: actions/upload-artifact@v2
        with: 
          name: 2b2w-ts-rewrite-win.exe
          path: pkg