# Publish GitHub workflow artifacts tutorial example
name: Build To Executable

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:


      - name: Checkout
        uses: actions/checkout@v3

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir pkg
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: npm run package
    
      - name: Step 3 - Use the Upload Artifact GitHub Action (Linux)
        uses: actions/upload-artifact@v2
        with: 
          name: 2b2w-ts-rewrite-linux
          path: pkg


      - name: Step 4 - Use the Upload Artifact GitHub Action (MacOS)
        uses: actions/upload-artifact@v2
        with: 
          name: 2b2w-ts-rewrite-macos
          path: pkg


      - name: Step 5 - Use the Upload Artifact GitHub Action (Windows)
        uses: actions/upload-artifact@v2
        with: 
          name: 2b2w-ts-rewrite-win.exe
          path: pkg